/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellPelangganRouteImport } from './routes/_shell.pelanggan'
import { Route as ShellRiwayatRouteImport } from './routes/_shell.riwayat'
import { Route as ShellServisRouteImport } from './routes/_shell.servis'
import { Route as ShellSparepartRouteImport } from './routes/_shell.sparepart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganRoute = ShellPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRiwayatRoute = ShellRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServisRoute = ShellServisRouteImport.update({
  id: '/servis',
  path: '/servis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSparepartRoute = ShellSparepartRouteImport.update({
  id: '/sparepart',
  path: '/sparepart',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/pelanggan': typeof ShellPelangganRoute
  '/riwayat': typeof ShellRiwayatRoute
  '/servis': typeof ShellServisRoute
  '/sparepart': typeof ShellSparepartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/pelanggan': typeof ShellPelangganRoute
  '/riwayat': typeof ShellRiwayatRoute
  '/servis': typeof ShellServisRoute
  '/sparepart': typeof ShellSparepartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/pelanggan': typeof ShellPelangganRoute
  '/_shell/riwayat': typeof ShellRiwayatRoute
  '/_shell/servis': typeof ShellServisRoute
  '/_shell/sparepart': typeof ShellSparepartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/pelanggan' | '/riwayat' | '/servis' | '/sparepart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/pelanggan' | '/riwayat' | '/servis' | '/sparepart'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/pelanggan'
    | '/_shell/riwayat'
    | '/_shell/servis'
    | '/_shell/sparepart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan': {
      id: '/_shell/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof ShellPelangganRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/riwayat': {
      id: '/_shell/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof ShellRiwayatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/servis': {
      id: '/_shell/servis'
      path: '/servis'
      fullPath: '/servis'
      preLoaderRoute: typeof ShellServisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sparepart': {
      id: '/_shell/sparepart'
      path: '/sparepart'
      fullPath: '/sparepart'
      preLoaderRoute: typeof ShellSparepartRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellPelangganRoute: typeof ShellPelangganRoute
  ShellRiwayatRoute: typeof ShellRiwayatRoute
  ShellServisRoute: typeof ShellServisRoute
  ShellSparepartRoute: typeof ShellSparepartRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellPelangganRoute: ShellPelangganRoute,
  ShellRiwayatRoute: ShellRiwayatRoute,
  ShellServisRoute: ShellServisRoute,
  ShellSparepartRoute: ShellSparepartRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
