/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellProfilRouteImport } from './routes/_shell.profil'
import { Route as ShellAdminBookingRouteImport } from './routes/_shell.admin.booking'
import { Route as ShellAdminCsRouteImport } from './routes/_shell.admin.cs'
import { Route as ShellAdminDashboardRouteImport } from './routes/_shell.admin.dashboard'
import { Route as ShellAdminLaporanRouteImport } from './routes/_shell.admin.laporan'
import { Route as ShellAdminServisRouteImport } from './routes/_shell.admin.servis'
import { Route as ShellAdminSparepartRouteImport } from './routes/_shell.admin.sparepart'
import { Route as ShellAdminStokRouteImport } from './routes/_shell.admin.stok'
import { Route as ShellOwnerDashboardRouteImport } from './routes/_shell.owner.dashboard'
import { Route as ShellOwnerKeuntunganRouteImport } from './routes/_shell.owner.keuntungan'
import { Route as ShellOwnerPelangganRouteImport } from './routes/_shell.owner.pelanggan'
import { Route as ShellOwnerServisRouteImport } from './routes/_shell.owner.servis'
import { Route as ShellOwnerSparepartRouteImport } from './routes/_shell.owner.sparepart'
import { Route as ShellPelangganBookingRouteImport } from './routes/_shell.pelanggan.booking'
import { Route as ShellPelangganCsRouteImport } from './routes/_shell.pelanggan.cs'
import { Route as ShellPelangganDashboardRouteImport } from './routes/_shell.pelanggan.dashboard'
import { Route as ShellPelangganEstimasiRouteImport } from './routes/_shell.pelanggan.estimasi'
import { Route as ShellPelangganKendaraanRouteImport } from './routes/_shell.pelanggan.kendaraan'
import { Route as ShellPelangganPembayaranRouteImport } from './routes/_shell.pelanggan.pembayaran'
import { Route as ShellPelangganRiwayatRouteImport } from './routes/_shell.pelanggan.riwayat'
import { Route as ShellPelangganStatusRouteImport } from './routes/_shell.pelanggan.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellProfilRoute = ShellProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminBookingRoute = ShellAdminBookingRouteImport.update({
  id: '/admin/booking',
  path: '/admin/booking',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminCsRoute = ShellAdminCsRouteImport.update({
  id: '/admin/cs',
  path: '/admin/cs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminDashboardRoute = ShellAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminLaporanRoute = ShellAdminLaporanRouteImport.update({
  id: '/admin/laporan',
  path: '/admin/laporan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminServisRoute = ShellAdminServisRouteImport.update({
  id: '/admin/servis',
  path: '/admin/servis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminSparepartRoute = ShellAdminSparepartRouteImport.update({
  id: '/admin/sparepart',
  path: '/admin/sparepart',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminStokRoute = ShellAdminStokRouteImport.update({
  id: '/admin/stok',
  path: '/admin/stok',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerDashboardRoute = ShellOwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerKeuntunganRoute = ShellOwnerKeuntunganRouteImport.update({
  id: '/owner/keuntungan',
  path: '/owner/keuntungan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerPelangganRoute = ShellOwnerPelangganRouteImport.update({
  id: '/owner/pelanggan',
  path: '/owner/pelanggan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerServisRoute = ShellOwnerServisRouteImport.update({
  id: '/owner/servis',
  path: '/owner/servis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnerSparepartRoute = ShellOwnerSparepartRouteImport.update({
  id: '/owner/sparepart',
  path: '/owner/sparepart',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganBookingRoute = ShellPelangganBookingRouteImport.update({
  id: '/pelanggan/booking',
  path: '/pelanggan/booking',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganCsRoute = ShellPelangganCsRouteImport.update({
  id: '/pelanggan/cs',
  path: '/pelanggan/cs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganDashboardRoute = ShellPelangganDashboardRouteImport.update({
  id: '/pelanggan/dashboard',
  path: '/pelanggan/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganEstimasiRoute = ShellPelangganEstimasiRouteImport.update({
  id: '/pelanggan/estimasi',
  path: '/pelanggan/estimasi',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganKendaraanRoute = ShellPelangganKendaraanRouteImport.update({
  id: '/pelanggan/kendaraan',
  path: '/pelanggan/kendaraan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganPembayaranRoute =
  ShellPelangganPembayaranRouteImport.update({
    id: '/pelanggan/pembayaran',
    path: '/pelanggan/pembayaran',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellPelangganRiwayatRoute = ShellPelangganRiwayatRouteImport.update({
  id: '/pelanggan/riwayat',
  path: '/pelanggan/riwayat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPelangganStatusRoute = ShellPelangganStatusRouteImport.update({
  id: '/pelanggan/status',
  path: '/pelanggan/status',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profil': typeof ShellProfilRoute
  '/admin/booking': typeof ShellAdminBookingRoute
  '/admin/cs': typeof ShellAdminCsRoute
  '/admin/dashboard': typeof ShellAdminDashboardRoute
  '/admin/laporan': typeof ShellAdminLaporanRoute
  '/admin/servis': typeof ShellAdminServisRoute
  '/admin/sparepart': typeof ShellAdminSparepartRoute
  '/admin/stok': typeof ShellAdminStokRoute
  '/owner/dashboard': typeof ShellOwnerDashboardRoute
  '/owner/keuntungan': typeof ShellOwnerKeuntunganRoute
  '/owner/pelanggan': typeof ShellOwnerPelangganRoute
  '/owner/servis': typeof ShellOwnerServisRoute
  '/owner/sparepart': typeof ShellOwnerSparepartRoute
  '/pelanggan/booking': typeof ShellPelangganBookingRoute
  '/pelanggan/cs': typeof ShellPelangganCsRoute
  '/pelanggan/dashboard': typeof ShellPelangganDashboardRoute
  '/pelanggan/estimasi': typeof ShellPelangganEstimasiRoute
  '/pelanggan/kendaraan': typeof ShellPelangganKendaraanRoute
  '/pelanggan/pembayaran': typeof ShellPelangganPembayaranRoute
  '/pelanggan/riwayat': typeof ShellPelangganRiwayatRoute
  '/pelanggan/status': typeof ShellPelangganStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profil': typeof ShellProfilRoute
  '/admin/booking': typeof ShellAdminBookingRoute
  '/admin/cs': typeof ShellAdminCsRoute
  '/admin/dashboard': typeof ShellAdminDashboardRoute
  '/admin/laporan': typeof ShellAdminLaporanRoute
  '/admin/servis': typeof ShellAdminServisRoute
  '/admin/sparepart': typeof ShellAdminSparepartRoute
  '/admin/stok': typeof ShellAdminStokRoute
  '/owner/dashboard': typeof ShellOwnerDashboardRoute
  '/owner/keuntungan': typeof ShellOwnerKeuntunganRoute
  '/owner/pelanggan': typeof ShellOwnerPelangganRoute
  '/owner/servis': typeof ShellOwnerServisRoute
  '/owner/sparepart': typeof ShellOwnerSparepartRoute
  '/pelanggan/booking': typeof ShellPelangganBookingRoute
  '/pelanggan/cs': typeof ShellPelangganCsRoute
  '/pelanggan/dashboard': typeof ShellPelangganDashboardRoute
  '/pelanggan/estimasi': typeof ShellPelangganEstimasiRoute
  '/pelanggan/kendaraan': typeof ShellPelangganKendaraanRoute
  '/pelanggan/pembayaran': typeof ShellPelangganPembayaranRoute
  '/pelanggan/riwayat': typeof ShellPelangganRiwayatRoute
  '/pelanggan/status': typeof ShellPelangganStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/profil': typeof ShellProfilRoute
  '/_shell/admin/booking': typeof ShellAdminBookingRoute
  '/_shell/admin/cs': typeof ShellAdminCsRoute
  '/_shell/admin/dashboard': typeof ShellAdminDashboardRoute
  '/_shell/admin/laporan': typeof ShellAdminLaporanRoute
  '/_shell/admin/servis': typeof ShellAdminServisRoute
  '/_shell/admin/sparepart': typeof ShellAdminSparepartRoute
  '/_shell/admin/stok': typeof ShellAdminStokRoute
  '/_shell/owner/dashboard': typeof ShellOwnerDashboardRoute
  '/_shell/owner/keuntungan': typeof ShellOwnerKeuntunganRoute
  '/_shell/owner/pelanggan': typeof ShellOwnerPelangganRoute
  '/_shell/owner/servis': typeof ShellOwnerServisRoute
  '/_shell/owner/sparepart': typeof ShellOwnerSparepartRoute
  '/_shell/pelanggan/booking': typeof ShellPelangganBookingRoute
  '/_shell/pelanggan/cs': typeof ShellPelangganCsRoute
  '/_shell/pelanggan/dashboard': typeof ShellPelangganDashboardRoute
  '/_shell/pelanggan/estimasi': typeof ShellPelangganEstimasiRoute
  '/_shell/pelanggan/kendaraan': typeof ShellPelangganKendaraanRoute
  '/_shell/pelanggan/pembayaran': typeof ShellPelangganPembayaranRoute
  '/_shell/pelanggan/riwayat': typeof ShellPelangganRiwayatRoute
  '/_shell/pelanggan/status': typeof ShellPelangganStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profil'
    | '/admin/booking'
    | '/admin/cs'
    | '/admin/dashboard'
    | '/admin/laporan'
    | '/admin/servis'
    | '/admin/sparepart'
    | '/admin/stok'
    | '/owner/dashboard'
    | '/owner/keuntungan'
    | '/owner/pelanggan'
    | '/owner/servis'
    | '/owner/sparepart'
    | '/pelanggan/booking'
    | '/pelanggan/cs'
    | '/pelanggan/dashboard'
    | '/pelanggan/estimasi'
    | '/pelanggan/kendaraan'
    | '/pelanggan/pembayaran'
    | '/pelanggan/riwayat'
    | '/pelanggan/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profil'
    | '/admin/booking'
    | '/admin/cs'
    | '/admin/dashboard'
    | '/admin/laporan'
    | '/admin/servis'
    | '/admin/sparepart'
    | '/admin/stok'
    | '/owner/dashboard'
    | '/owner/keuntungan'
    | '/owner/pelanggan'
    | '/owner/servis'
    | '/owner/sparepart'
    | '/pelanggan/booking'
    | '/pelanggan/cs'
    | '/pelanggan/dashboard'
    | '/pelanggan/estimasi'
    | '/pelanggan/kendaraan'
    | '/pelanggan/pembayaran'
    | '/pelanggan/riwayat'
    | '/pelanggan/status'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/profil'
    | '/_shell/admin/booking'
    | '/_shell/admin/cs'
    | '/_shell/admin/dashboard'
    | '/_shell/admin/laporan'
    | '/_shell/admin/servis'
    | '/_shell/admin/sparepart'
    | '/_shell/admin/stok'
    | '/_shell/owner/dashboard'
    | '/_shell/owner/keuntungan'
    | '/_shell/owner/pelanggan'
    | '/_shell/owner/servis'
    | '/_shell/owner/sparepart'
    | '/_shell/pelanggan/booking'
    | '/_shell/pelanggan/cs'
    | '/_shell/pelanggan/dashboard'
    | '/_shell/pelanggan/estimasi'
    | '/_shell/pelanggan/kendaraan'
    | '/_shell/pelanggan/pembayaran'
    | '/_shell/pelanggan/riwayat'
    | '/_shell/pelanggan/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/profil': {
      id: '/_shell/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ShellProfilRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/booking': {
      id: '/_shell/admin/booking'
      path: '/admin/booking'
      fullPath: '/admin/booking'
      preLoaderRoute: typeof ShellAdminBookingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/cs': {
      id: '/_shell/admin/cs'
      path: '/admin/cs'
      fullPath: '/admin/cs'
      preLoaderRoute: typeof ShellAdminCsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/dashboard': {
      id: '/_shell/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ShellAdminDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/laporan': {
      id: '/_shell/admin/laporan'
      path: '/admin/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof ShellAdminLaporanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/servis': {
      id: '/_shell/admin/servis'
      path: '/admin/servis'
      fullPath: '/admin/servis'
      preLoaderRoute: typeof ShellAdminServisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/sparepart': {
      id: '/_shell/admin/sparepart'
      path: '/admin/sparepart'
      fullPath: '/admin/sparepart'
      preLoaderRoute: typeof ShellAdminSparepartRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/stok': {
      id: '/_shell/admin/stok'
      path: '/admin/stok'
      fullPath: '/admin/stok'
      preLoaderRoute: typeof ShellAdminStokRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/dashboard': {
      id: '/_shell/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof ShellOwnerDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/keuntungan': {
      id: '/_shell/owner/keuntungan'
      path: '/owner/keuntungan'
      fullPath: '/owner/keuntungan'
      preLoaderRoute: typeof ShellOwnerKeuntunganRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/pelanggan': {
      id: '/_shell/owner/pelanggan'
      path: '/owner/pelanggan'
      fullPath: '/owner/pelanggan'
      preLoaderRoute: typeof ShellOwnerPelangganRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/servis': {
      id: '/_shell/owner/servis'
      path: '/owner/servis'
      fullPath: '/owner/servis'
      preLoaderRoute: typeof ShellOwnerServisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owner/sparepart': {
      id: '/_shell/owner/sparepart'
      path: '/owner/sparepart'
      fullPath: '/owner/sparepart'
      preLoaderRoute: typeof ShellOwnerSparepartRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/booking': {
      id: '/_shell/pelanggan/booking'
      path: '/pelanggan/booking'
      fullPath: '/pelanggan/booking'
      preLoaderRoute: typeof ShellPelangganBookingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/cs': {
      id: '/_shell/pelanggan/cs'
      path: '/pelanggan/cs'
      fullPath: '/pelanggan/cs'
      preLoaderRoute: typeof ShellPelangganCsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/dashboard': {
      id: '/_shell/pelanggan/dashboard'
      path: '/pelanggan/dashboard'
      fullPath: '/pelanggan/dashboard'
      preLoaderRoute: typeof ShellPelangganDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/estimasi': {
      id: '/_shell/pelanggan/estimasi'
      path: '/pelanggan/estimasi'
      fullPath: '/pelanggan/estimasi'
      preLoaderRoute: typeof ShellPelangganEstimasiRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/kendaraan': {
      id: '/_shell/pelanggan/kendaraan'
      path: '/pelanggan/kendaraan'
      fullPath: '/pelanggan/kendaraan'
      preLoaderRoute: typeof ShellPelangganKendaraanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/pembayaran': {
      id: '/_shell/pelanggan/pembayaran'
      path: '/pelanggan/pembayaran'
      fullPath: '/pelanggan/pembayaran'
      preLoaderRoute: typeof ShellPelangganPembayaranRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/riwayat': {
      id: '/_shell/pelanggan/riwayat'
      path: '/pelanggan/riwayat'
      fullPath: '/pelanggan/riwayat'
      preLoaderRoute: typeof ShellPelangganRiwayatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pelanggan/status': {
      id: '/_shell/pelanggan/status'
      path: '/pelanggan/status'
      fullPath: '/pelanggan/status'
      preLoaderRoute: typeof ShellPelangganStatusRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellProfilRoute: typeof ShellProfilRoute
  ShellAdminBookingRoute: typeof ShellAdminBookingRoute
  ShellAdminCsRoute: typeof ShellAdminCsRoute
  ShellAdminDashboardRoute: typeof ShellAdminDashboardRoute
  ShellAdminLaporanRoute: typeof ShellAdminLaporanRoute
  ShellAdminServisRoute: typeof ShellAdminServisRoute
  ShellAdminSparepartRoute: typeof ShellAdminSparepartRoute
  ShellAdminStokRoute: typeof ShellAdminStokRoute
  ShellOwnerDashboardRoute: typeof ShellOwnerDashboardRoute
  ShellOwnerKeuntunganRoute: typeof ShellOwnerKeuntunganRoute
  ShellOwnerPelangganRoute: typeof ShellOwnerPelangganRoute
  ShellOwnerServisRoute: typeof ShellOwnerServisRoute
  ShellOwnerSparepartRoute: typeof ShellOwnerSparepartRoute
  ShellPelangganBookingRoute: typeof ShellPelangganBookingRoute
  ShellPelangganCsRoute: typeof ShellPelangganCsRoute
  ShellPelangganDashboardRoute: typeof ShellPelangganDashboardRoute
  ShellPelangganEstimasiRoute: typeof ShellPelangganEstimasiRoute
  ShellPelangganKendaraanRoute: typeof ShellPelangganKendaraanRoute
  ShellPelangganPembayaranRoute: typeof ShellPelangganPembayaranRoute
  ShellPelangganRiwayatRoute: typeof ShellPelangganRiwayatRoute
  ShellPelangganStatusRoute: typeof ShellPelangganStatusRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellProfilRoute: ShellProfilRoute,
  ShellAdminBookingRoute: ShellAdminBookingRoute,
  ShellAdminCsRoute: ShellAdminCsRoute,
  ShellAdminDashboardRoute: ShellAdminDashboardRoute,
  ShellAdminLaporanRoute: ShellAdminLaporanRoute,
  ShellAdminServisRoute: ShellAdminServisRoute,
  ShellAdminSparepartRoute: ShellAdminSparepartRoute,
  ShellAdminStokRoute: ShellAdminStokRoute,
  ShellOwnerDashboardRoute: ShellOwnerDashboardRoute,
  ShellOwnerKeuntunganRoute: ShellOwnerKeuntunganRoute,
  ShellOwnerPelangganRoute: ShellOwnerPelangganRoute,
  ShellOwnerServisRoute: ShellOwnerServisRoute,
  ShellOwnerSparepartRoute: ShellOwnerSparepartRoute,
  ShellPelangganBookingRoute: ShellPelangganBookingRoute,
  ShellPelangganCsRoute: ShellPelangganCsRoute,
  ShellPelangganDashboardRoute: ShellPelangganDashboardRoute,
  ShellPelangganEstimasiRoute: ShellPelangganEstimasiRoute,
  ShellPelangganKendaraanRoute: ShellPelangganKendaraanRoute,
  ShellPelangganPembayaranRoute: ShellPelangganPembayaranRoute,
  ShellPelangganRiwayatRoute: ShellPelangganRiwayatRoute,
  ShellPelangganStatusRoute: ShellPelangganStatusRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
